# Generated by Django 3.1 on 2020-08-14 22:02

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False)),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('state', models.CharField(choices=[('n', 'New'), ('p', 'In Progress'), ('d', 'Done')], default='n', max_length=1)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked', to='task2.task')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
